services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: TuPassword123
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  go-api-find-my-friend:
    image: go-api-find-my-friend:latest
    container_name: backend_container
    depends_on:
      - sqlserver
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: TuPassword123
      DB_NAME: find-my-friend
    ports:
      - "8080:8080"
    restart: unless-stopped

  react-find-my-friend:
    image: react-find-my-friend:latest
    container_name: frontend_container
    depends_on:
      - go-api-find-my-friend
    environment:
      VITE_API_BASE_URL: "http://localhost:8080/api/v1"
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - react-find-my-friend
      - go-api-find-my-friend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  sqlserver_data: