package models

var (
	PetTypes = []string{"perro", "gato", "otro"}

	PetBreeds = map[string][]string{
		"perro": {"labrador", "german shepherd", "golden retriever", "poodle", "beagle", "pug", "bulldog", "pomeranian", "schnauzer", "chihuahua", "shih tzu", "yorkshire terrier", "pomeranian", "schnauzer", "chihuahua", "shih tzu", "yorkshire terrier"},
		"gato":  {"siamese", "persian", "maine coon", "ragdoll", "siberian", "british shorthair", "scottish fold", "ragdoll", "siberian", "british shorthair", "scottish fold"},
		"otro":  {"pajaro", "conejo", "hamster", "canchito de las indias", "pez", "serpiente", "tortuga", "lagartija", "otro"},
	}

	CitiesByProvince = map[string][]string{
		"Buenos Aires": {
			"Buenos Aires",
			"La Plata",
			"Mar del Plata",
			"Bahía Blanca",
			"Tandil",
			"Olavarría",
			"San Nicolás",
			"Quilmes",
			"Avellaneda",
			"Lanús",
		},
		"Córdoba": {
			"Córdoba",
			"Río Cuarto",
			"Villa María",
			"San Francisco",
			"Villa Carlos Paz",
			"Alta Gracia",
			"Bell Ville",
			"Villa Dolores",
			"Cosquín",
			"Jesús María",
		},
		"Santa Fe": {
			"Rosario",
			"Santa Fe",
			"Rafaela",
			"Villa Gobernador Gálvez",
			"Venado Tuerto",
			"San Lorenzo",
			"Santo Tomé",
			"San Cristóbal",
			"Reconquista",
			"Esperanza",
		},
		"Mendoza": {
			"Mendoza",
			"Godoy Cruz",
			"Las Heras",
			"San Rafael",
			"Tunuyán",
			"San Martín",
			"Luján de Cuyo",
			"Maipú",
			"Rivadavia",
			"General Alvear",
		},
		"Tucumán": {
			"San Miguel de Tucumán",
			"Yerba Buena",
			"Tafí Viejo",
			"Banda del Río Salí",
			"Aguilares",
			"Monteros",
			"Concepción",
			"Famaillá",
			"Lules",
			"Burruyacú",
		},
		"Salta": {
			"Salta",
			"San Ramón de la Nueva Orán",
			"Tartagal",
			"General Güemes",
			"Metán",
			"Cafayate",
			"Cerrillos",
			"Rosario de Lerma",
			"La Caldera",
			"Chicoana",
		},
		"Entre Ríos": {
			"Paraná",
			"Concordia",
			"Gualeguaychú",
			"Concepción del Uruguay",
			"Gualeguay",
			"Villaguay",
			"Colón",
			"Victoria",
			"Federación",
			"Diamante",
		},
		"San Juan": {
			"San Juan",
			"Rawson",
			"Rivadavia",
			"Pocito",
			"Chimbas",
			"Caucete",
			"Albardón",
			"Angaco",
			"San Martín",
			"Sarmiento",
		},
		"Neuquén": {
			"Neuquén",
			"Cutral Co",
			"Plottier",
			"Centenario",
			"San Martín de los Andes",
			"Zapala",
			"Villa La Angostura",
			"Chos Malal",
			"Aluminé",
			"Junín de los Andes",
		},
		"Chaco": {
			"Resistencia",
			"Barranqueras",
			"Presidencia Roque Sáenz Peña",
			"Villa Ángela",
			"Charata",
			"General San Martín",
			"Quitilipi",
			"Machagai",
			"Villa Berthet",
			"Las Breñas",
		},
		"Santiago del Estero": {
			"Santiago del Estero",
			"La Banda",
			"Termas de Río Hondo",
			"Añatuya",
			"Frías",
			"Monte Quemado",
			"Villa Ojo de Agua",
			"Loreto",
			"Pinto",
			"Selva",
		},
		"Corrientes": {
			"Corrientes",
			"Goya",
			"Paso de los Libres",
			"Mercedes",
			"Curuzú Cuatiá",
			"Monte Caseros",
			"Bella Vista",
			"Esquina",
			"Santo Tomé",
			"Empedrado",
		},
		"San Luis": {
			"San Luis",
			"Villa Mercedes",
			"Merlo",
			"La Punta",
			"Concarán",
			"Villa de la Quebrada",
			"Villa General Roca",
			"Villa General Roca",
			"Nueva Galia",
			"San Francisco del Monte de Oro",
			"La Toma",
		},
		"Formosa": {
			"Formosa",
			"Clorinda",
			"Pirané",
			"El Colorado",
			"Las Lomitas",
			"Comandante Fontana",
			"Laguna Yema",
			"Pozo del Tigre",
			"Villa General Güemes",
			"Ibarreta",
		},
		"Jujuy": {
			"San Salvador de Jujuy",
			"Palpalá",
			"San Pedro de Jujuy",
			"Perico",
			"Libertador General San Martín",
			"El Carmen",
			"Fraile Pintado",
			"La Quiaca",
			"Humahuaca",
			"Tilcara",
		},
		"Misiones": {
			"Posadas",
			"Oberá",
			"Eldorado",
			"Puerto Iguazú",
			"San Vicente",
			"Apostoles",
			"Leandro N. Alem",
			"Jardín América",
			"Montecarlo",
			"Puerto Rico",
		},
	}
)
